# This is a config for E2B sandbox template.
# You can use template ID (0trgdnec5qh32vt0rnre) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox.create("0trgdnec5qh32vt0rnre") # Sync sandbox
# sandbox = await AsyncSandbox.create("0trgdnec5qh32vt0rnre") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('0trgdnec5qh32vt0rnre')

team_id = "e1e4b8ba-29af-45f5-a32b-4b3647a53355"
dockerfile = "e2b.Dockerfile"
template_id = "0trgdnec5qh32vt0rnre"
